micronaut:
  server:
    max-request-size: '100GB'
    multipart:
      max-file-size: '100GB'
  application:
    name: wormhole
  caches:
    registry:
      maximum-size: 20
      expire-after-write: 30m
netty:
  default:
    allocator:
      max-order: 3
